# Generated by Django 5.0.4 on 2024-05-06 14:56

import django.db.models.deletion
import miniagents_copilot.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hash_key", models.CharField(max_length=64, unique=True)),
                ("node_class", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField()),
                ("created_timestamp_ms", models.BigIntegerField(default=miniagents_copilot.utils.current_time_utc_ms)),
                ("touched_timestamp_ms", models.BigIntegerField(default=miniagents_copilot.utils.current_time_utc_ms)),
            ],
        ),
        migrations.CreateModel(
            name="LangModelGenerationStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp_ms", models.BigIntegerField(default=miniagents_copilot.utils.current_time_utc_ms)),
                ("model_name", models.TextField(blank=True, null=True)),
                ("input_token_num", models.IntegerField(blank=True, null=True)),
                ("output_token_num", models.IntegerField(blank=True, null=True)),
                (
                    "data_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="miniagents_copilot.datanode",
                    ),
                ),
            ],
        ),
    ]
